#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "jmthonar" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw=" | base64 -d
    elif [[ $UPSTREAM_REPO == "jmthonar" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw=" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="JmthonBot.zip"
    echo "  يتم تحميل ملفات سورس جمثون ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  فك بيانات السورس ..."
    JMTHONPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "✓"
    echo "  يتم التفريغ.."
    rm -rf "$zippath"
    sleep 5
    cd $JMTHONPATH
    echo "    بدء بوت جمثون    "
    echo "
                       
╋╋╋╋╋┏┓┏┓
╋┏┳━━┫┗┫┗┳━┳━┳┓
╋┣┫┃┃┃┏┫┃┃╋┃┃┃┃
┏┛┣┻┻┻━┻┻┻━┻┻━┛
┗━┛
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
